Readme Actualizado
nschurmann/mongoapp-curso-docker pull request #2
Opened 2022-08-08 19:26 UTC by pcabreram1234

He actualizado el readme en base a los apuntes creo son los más relevantes en ese gran curso, espero sean de tu agradas y hagas merge de los que creas necesarios.

2022-08-23 14:13 UTC, pcabreram1234 commented
Buenos días, espero estés bien @nschurmann  dentro de lo posible para que verifiques este Pull Request.

2023-03-05 13:32 UTC, dr-nefardio3058 requested changes
Buenas Phillip,

Esta muy bueno lo que has hecho, pero se puede mejorar:

- Creo que sería mejor poner todo este resumen del curso en un archivo del repositorio y no en el readme, ya que lo llena mucho. 

- En la primera parte faltan signos, como en el "que es" ---> "¿Qué es?" y algunos : (en todo el readme.md)

- Podrías poner el link del final como hipevinculo con [aquí](url del video).

Esas son algunas sugerencias Phillip, cabe destacar que esta muy bueno tu trabajo y espero así que sea mergeado.

Ten un excelente día.

2023-03-05 14:49 UTC, pcabreram1234 commented
Buenos días, muchas gracias por la respuesta a mi solicitud he agregado el archivo Resume.md y he realizado los siguientes cambios:

<p>
- [ x ] Creo que sería mejor poner todo este resumen del curso en un archivo aparte del repositorio y no en el readme, ya que lo llena mucho. El readme es solo una introducción al curso, no el resumen.
</p>

<p>
- [ x ] En la primera parte y en gran parte del readme faltan signos y hay errores de ortografía, como en el "que es" conviértelo en ---> "¿Qué es?" y algunos :
</p>

<p>
- [ x ]Podrías poner el link del final como hipervínculo con [aquí](url del video).
</p>


Podrías poner el link del final como hipervínculo con [aquí](url del video).

2023-03-05 14:52 UTC, dr-nefardio3058 approved these changes
**Muy bien. Ahora si Phillip, espero que esta PR sea mergeada.** 👍 

> Además, estoy a punto de publicar una PR en tu portfolio corrigiendo algunos errores de ortografía, checkéala. 😸

2023-03-10 00:40 UTC, dr-nefardio3058 commented
### Hola Phillip,

**Te quería dar gracias por esta Pull Request y todo su contenido, ya que yo había hecho el curso pero sin querer elimine los archivos; y con el contenido de esta PR los he recuperado. Muchas grcias Phillip. _Si tú no estarías tendria que ver y resumir el curso denuevo._**

> Gracias amigo.

2023-03-10 10:50 UTC, pcabreram1234 commented
Un placer espero que esta PR pueda ser mergeada.

2023-10-29 22:12 UTC, rvjaraj approved these changes

2023-10-29 22:23 UTC, nschurmann approved these changes
LGTM!

2023-10-29 22:23 UTC, merged